In [2]:
import numpy as np
import cv2

Attempt1: using library for edge detection

In [3]:
image = cv2.imread(r'C:\Users\vtminh\Documents\UMass deadly\2nd year\why many folder\Img_Edge_Detect\image.jpg')
ddepth1 = cv2.CV_64F
ddepth2 = cv2.CV_64F

# print(image.shape)
# print(image)

scale_percent = 100
width = int(image.shape[1] * scale_percent / 100)
height = int(image.shape[0] * scale_percent / 100)
dim = (width, height)

resized = cv2.resize(image, dim)

gray = cv2.cvtColor(resized, cv2.COLOR_BGR2GRAY)
blurred = cv2.GaussianBlur(resized,(3,3),cv2.BORDER_ISOLATED)
sharpen1 = cv2.Sobel(gray, ddepth1, 1, 0, ksize=3, scale = 1, delta = 30, borderType = cv2.BORDER_DEFAULT)
sharpen2 = cv2.Sobel(gray, ddepth2, 1, 0, ksize=3, scale = 1, delta = 0, borderType = cv2.BORDER_DEFAULT)

Attempt2: recreating the library :)))

In [4]:
img = cv2.imread(r'C:\Users\vtminh\Documents\UMass deadly\2nd year\why many folder\Img_Edge_Detect\image.jpg')

print(img.shape)
print(img)

(1080, 1919, 3)
[[[166 161 143]
  [165 159 142]
  [166 161 143]
  ...
  [ 62  74  81]
  [ 62  74  81]
  [ 65  76  83]]

 [[166 161 143]
  [168 163 146]
  [170 164 147]
  ...
  [ 66  77  84]
  [ 67  78  86]
  [ 66  77  84]]

 [[166 161 143]
  [166 161 143]
  [167 162 144]
  ...
  [ 67  78  86]
  [ 67  78  86]
  [ 64  75  82]]

 ...

 [[ 37  41  29]
  [ 38  42  30]
  [ 37  41  29]
  ...
  [120 111 103]
  [121 112 104]
  [121 112 104]]

 [[ 37  41  29]
  [ 38  42  30]
  [ 35  39  27]
  ...
  [122 113 105]
  [121 112 104]
  [121 112 104]]

 [[ 33  37  25]
  [ 34  38  26]
  [ 38  42  30]
  ...
  [120 111 103]
  [120 111 103]
  [118 110 102]]]


In [5]:
# creating grey image
def grayScale(r, g, b):
  x = r * 0.299 + g * 0.587 + b * 0.114
  return x

img[0][0] = grayScale(img[0][0][0], img[0][0][1], img[0][0][2])
print(img)

[[[160 160 160]
  [165 159 142]
  [166 161 143]
  ...
  [ 62  74  81]
  [ 62  74  81]
  [ 65  76  83]]

 [[166 161 143]
  [168 163 146]
  [170 164 147]
  ...
  [ 66  77  84]
  [ 67  78  86]
  [ 66  77  84]]

 [[166 161 143]
  [166 161 143]
  [167 162 144]
  ...
  [ 67  78  86]
  [ 67  78  86]
  [ 64  75  82]]

 ...

 [[ 37  41  29]
  [ 38  42  30]
  [ 37  41  29]
  ...
  [120 111 103]
  [121 112 104]
  [121 112 104]]

 [[ 37  41  29]
  [ 38  42  30]
  [ 35  39  27]
  ...
  [122 113 105]
  [121 112 104]
  [121 112 104]]

 [[ 33  37  25]
  [ 34  38  26]
  [ 38  42  30]
  ...
  [120 111 103]
  [120 111 103]
  [118 110 102]]]


In [7]:
copyImg = img
for i in range(len(copyImg)):
  for j in range(len(copyImg[i])):
    img[i][j] = grayScale(img[i][j][0], img[i][j][1], img[i][j][2])


In [8]:
# padding method
def padding(matrix_3d, pad):
  matrix_3d = np.pad(matrix_3d, ((pad, pad), (pad, pad), (0, 0)), 
                      'constant')
  return matrix_3d

arr = np.array([[[1,2],[3,4]],
                [[3,5],[2,6]],
                [[3,5],[2,6]]])
print(arr.shape[0])
print(padding(arr, 2))

3
[[[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [1 2]
  [3 4]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [3 5]
  [2 6]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [3 5]
  [2 6]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]
  [0 0]]]


In [9]:
# creating kernel
def kernel(k):
  if(k % 2 == 0):
    Exception("bruh bro")
  else:
    midInd = int((k - 1)/2)
    print(midInd)
    ker = np.ones((k, k), dtype = int) * (-1)
    ker[midInd][midInd] = int(k*k) - 1
    return ker

print(kernel(5))

2
[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 24 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


In [10]:
# convolution function
def convolution(origMat, k, s, p):
  newMat = padding(origMat, p)
  newWidth = int((len(newMat) - k + 2 * p)/s + 1)
  newLength = int((len(newMat[0]) - k + 2 * p)/s + 1)
  ker = kernel(k)

  res = np.zeros((newWidth, newLength))
  for i in range(0, newWidth, s):
    for j in range(0, newLength, s):
      tmpArr = newMat[0 + i : k + i, 0 + j : k + j]
      val = np.sum(np.multiply(ker, tmpArr))
      res[i][j] = val
  return res

cv2.imshow(convolution(copyImg, 3, 1, 0))

#Funny how it works well on colab but not here :v